# Generated by Django 3.0.6 on 2021-02-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='grjlC',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='grjlCT',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='grjlE',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='grjlET',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
